name: PROD CI/CD

on:
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] 

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run build

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 209.46.124.109
        username: ${{ secrets.FTP_USER_DEV }}
        password: ${{ secrets.FTP_PASSWORD_DEV }}
        local-dir: ./dist/pim/
        dangerous-clean-slate: true