import { Translation } from 'primeng/api';

export const Global = {
  translations: {
    startsWith: 'Empieza con',
    contains: 'Contiene',
    notContains: 'No contiene',
    endsWith: 'Termina con',
    equals: 'Igual a',
    notEquals: 'No es igual a',
    noFilter: 'Sin filtro',
    lt: 'Menor que',
    lte: 'Menor o igual que',
    gt: 'Mayor que',
    gte: 'Mayor o igual que',
    is: 'Es',
    isNot: 'No es',
    before: 'Antes de',
    after: 'Después de',
    dateIs: 'Fecha es',
    dateIsNot: 'Fecha no es',
    dateBefore: 'Fecha antes de',
    dateAfter: 'Fecha después de',
    clear: 'Limpiar',
    apply: 'Aplicar',
    matchAll: 'Coincidir con todos',
    matchAny: 'Coincidir con alguno',
    addRule: 'Agregar regla',
    removeRule: 'Eliminar regla',
    accept: 'Aceptar',
    reject: 'Rechazar',
    choose: 'Elegir',
    upload: 'Subir',
    cancel: 'Cancelar',
    fileSizeTypes: ['B', 'KB', 'MB', 'GB'],
    dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
    dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
    dayNamesMin: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
    monthNames: [
      'Enero',
      'Febrero',
      'Marzo',
      'Abril',
      'Mayo',
      'Junio',
      'Julio',
      'Agosto',
      'Septiembre',
      'Octubre',
      'Noviembre',
      'Diciembre',
    ],
    monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
    dateFormat: 'dd/mm/yy',
    firstDayOfWeek: 0,
    today: 'Hoy',
    weekHeader: 'Sem',
    weak: 'Débil',
    medium: 'Media',
    strong: 'Fuerte',
    passwordPrompt: 'Ingresa tu contraseña',
    emptyMessage: 'No hay información que mostrar',
    emptyFilterMessage: 'No se encontraron resultados',
    fileChosenMessage: 'Archivo seleccionado',
    noFileChosenMessage: 'No hay archivo seleccionado',
    pending: 'Pendiente',
    chooseYear: 'Elegir año',
    chooseMonth: 'Elegir mes',
    chooseDate: 'Elegir fecha',
    prevDecade: 'Década anterior',
    nextDecade: 'Siguiente década',
    prevYear: 'Año anterior',
    nextYear: 'Siguiente año',
    prevMonth: 'Mes anterior',
    nextMonth: 'Siguiente mes',
    prevHour: 'Hora anterior',
    nextHour: 'Siguiente hora',
    prevMinute: 'Minuto anterior',
    nextMinute: 'Siguiente minuto',
    prevSecond: 'Segundo anterior',
    nextSecond: 'Siguiente segundo',
    am: 'AM',
    pm: 'PM',
    searchMessage: 'Buscar...',
    selectionMessage: 'Seleccionados {0} de {1}',
    emptySelectionMessage: 'No hay elementos seleccionados',
    emptySearchMessage: 'No se encontraron coincidencias',
    aria: {
      trueLabel: 'verdadero',
      falseLabel: 'falso',
    },
  } as Translation,
};
